plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
nodeLinker: "pnp"
packageExtensions:
  graphile-build@*:
    dependencies:
      graphql: "^15.4.0"
  graphile-build-pg@*:
    dependencies:
      graphql: "^15.4.0"
  chartjs-adapter-date-fns@*:
    peerDependencies:
      date-fns: "*"